apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 940168446867.dkr.ecr.ap-northeast-3.amazonaws.com/demo-frontend
  newName: 940168446867.dkr.ecr.ap-northeast-3.amazonaws.com/demo-frontend
  newTag: 65c5829c
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
